version: "3.5"

volumes:
    mariadb_vol:
        
    wordpress_vol:

networks:
  inception_netw:
    driver: bridge

services:
  nginx:
    depends_on:
      - wordpress
    container_name: cont_nginx
    build: ./requirements/nginx
    networks:
      - inception_netw
    ports:
      - 443:443
    env_file:
      - .env

  mariadb:
    container_name: cont_mariadb
    volumes:
      - mariadb_vol:/home/kmendes-/data
    build: ./requirements/mariadb
    networks:
      - inception_netw
    ports:
      - 3306:3306
    env_file:
      - .env


  wordpress:
    depends_on:
      - mariadb
    container_name: cont_wordpress
    volumes:
      - wordpress_vol:/home/kmendes-/data
    build: ./requirements/wordpress
    networks:
      - inception_netw
    ports:
      - 9000:9000
    env_file:
      - .env
    environment:
      MYSQL_USER: kmendes-
      MYSQL_PASSWORD: qwertyuiop
      
      