version: "3.5"

volumes:
    mariadb_vol:
      driver: local
      name: mariadb_vol
      driver_opts:
        type: none
        o: bind
        device: /home/kmendes-/data/mysql
        
    wordpress_vol:
      driver: local
      name: wordpress_vol
      driver_opts:
        type: none
        o: bind
        device: /home/kmendes-/data/wordpress

networks:
  inception_netw:
    driver: bridge

services:
  nginx:
    depends_on:
      - wordpress
    volumes:
      - wordpress_vol:/var/www/html
    container_name: nginx
    build: ./requirements/nginx
    networks:
      - inception_netw
    ports:
      - 443:443
    env_file:
      - .env

  mariadb:
    container_name: mariadb
    volumes:
      - mariadb_vol:/var/lib/mysql
    build: ./requirements/mariadb
    networks:
      - inception_netw
    ports:
      - 3306:3306
    env_file:
      - .env


  wordpress:
    depends_on:
      - mariadb
    container_name: wordpress
    volumes:
      - wordpress_vol:/var/www/html
    build: ./requirements/wordpress
    networks:
      - inception_netw
    ports:
      - 9000:9000
    env_file:
      - .env
      
      
